apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daemon-monitor-backend.fullname" . }}-config
  labels:
    {{- include "daemon-monitor-backend.labels" . | nindent 4 }}
data:
  dbHost: {{ .Values.config.dbHost | quote }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName | quote }}
  debugMode: {{ .Values.config.debugMode | quote }}
  mysqlConfig: "{{ .Values.config.mysqlConfig }}"
