apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.database.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storage.storageClassName }}
  hostPath:
    path: {{ .Values.database.storage.path | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
  volumeName: mysql-pv
  storageClassName: {{ .Values.database.storage.storageClassName }}
